; Listing generated by Microsoft (R) Optimizing Compiler Version 19.22.27905.0 

	TITLE	c:\code\c++\personal\refptrtest\refptrtest\main.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

EXTRN	@__security_check_cookie@4:PROC
PUBLIC	_main
; Function compile flags: /Ogtp
;	COMDAT _main
_TEXT	SEGMENT
_main	PROC						; COMDAT
; File C:\Code\C++\Personal\RefPtrTest\RefPtrTest\main.cpp
; Line 17
	xor	eax, eax
; Line 18
	ret	0
_main	ENDP
_TEXT	ENDS
END
